name: Build

runs-on: ubuntu-latest

on:
  push:
    branches:
      - main
  pull_request:

strategy:
  matrix:
    node-version: [16.x,18.x]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build --if-present
      - run: npm test

